version: '3'
services:
  sample-api:
    build: .
    ports:
      - 3000:3000
    environment:
      - 'NODE_ENV=${NODE_ENV}'
    restart: unless-stopped
    networks:
      - sample-api
    volumes:
      - ${PWD}/:/app

networks:
  sample-api:
    external: false
